// Allow importing css modules and global css files in TypeScript
declare module '*.css'
declare module '*.module.css'
declare module '*.scss'
declare module '*.module.scss'
declare module '*.sass'
declare module '*.module.sass'
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.webp'
